"""Build a Q-SHIELD case from real X.509 certificates.

This is the module that decides whether Q-SHIELD is usable on anything but its
own synthetic instances. Everything before it ran on generated inventories; this
turns a directory of PEM files, or a list of live TLS endpoints, into a case the
planner can act on.

It fits better than it has any right to. The 0.5 model needed two things the
earlier versions could not express — how long a signing credential stays in
service, and which authority a credential inherits its trust from — and a
certificate carries both, exactly and unambiguously:

* ``notBefore``/``notAfter`` **is** the credential-validity horizon that
  :mod:`qshield.threat` selects for ``AUTHENTICATION`` assets;
* issuer/subject (refined by authority and subject key identifiers) **is** the
  delegation edge that :func:`qshield.model.effective_node_risk` propagates
  along;
* the subject public key **is** the algorithm to migrate, and its size
  distinguishes RSA-2048 from RSA-4096;
* a codeSigning EKU **is** a statement that the artifacts outlive the key, which
  is what ``NON_REPUDIATION`` means.

What no certificate carries is equally important: sensitivity, exposure, data
lifetime, business criticality, migration cost and rotation cadence appear
nowhere in X.509. Those are filled with documented placeholders and recorded as
``ASSUMED`` in the provenance, never quietly. See
:mod:`qshield.ingest.provenance`.

Requires the ``scan`` extra (``pip install qshield[scan]``); the core model and
every experiment stay dependency-free, so a result cannot shift because a parser
changed.
"""

from __future__ import annotations

import _ssl
import datetime
import socket
import ssl
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

from ..model import AssetModel
from ..paths import EdgeKind, EdgeModel
from ..threat import ThreatClass
from .provenance import AssetProvenance, InventoryProvenance

try:  # pragma: no cover - exercised by the import-error test
    from cryptography import x509
    from cryptography.hazmat.primitives.asymmetric import ec, ed448, ed25519, rsa
    from cryptography.x509.oid import ExtendedKeyUsageOID
except ImportError as exc:  # pragma: no cover
    raise ImportError(
        "X.509 ingest needs the 'scan' extra: pip install 'qshield[scan]'"
    ) from exc

# _ssl exposes the encoding constants that ssl does not re-export; the chain
# objects returned by get_unverified_chain need one to serialise.
_DER = _ssl.ENCODING_DER

DAYS_PER_YEAR = 365.25
PEM_SUFFIXES = {".pem", ".crt", ".cer", ".ca-bundle", ".chain"}
DER_SUFFIXES = {".der"}

# Placeholders for the six parameters X.509 cannot supply. Chosen to be plainly
# provisional rather than plausible: a reviewer should notice them.
ASSUMED_SENSITIVITY = 0.7
ASSUMED_DATA_LIFETIME_YEARS = 10.0
ASSUMED_BUSINESS_CRITICALITY = 0.8
# Exposure and cost vary with the one thing a certificate does tell us -- whether
# it is an authority or an endpoint -- so they are split rather than flat.
ASSUMED_EXPOSURE_CA = 0.25          # authorities are usually offline or restricted
ASSUMED_EXPOSURE_LEAF = 0.85        # endpoints terminate untrusted traffic
ASSUMED_COST_ROOT = 5.0             # a root migration is a trust-store programme
ASSUMED_COST_INTERMEDIATE = 2.0
ASSUMED_COST_LEAF = 0.5             # usually one automated re-issue
ASSUMED_ROTATION_HOURS_CA = 0.0     # authorities are not rotated on a cadence
ASSUMED_ROTATION_HOURS_LEAF = 24.0

# A signed artifact typically has to verify long after the key that signed it is
# gone. 25 years is a placeholder; set verification_horizon_years for real.
ASSUMED_VERIFICATION_HORIZON_YEARS = 25.0


class CertificateIngestError(ValueError):
    """A certificate could not be turned into an asset."""


@dataclass
class Inventory:
    """A case assembled from artifacts, with its provenance attached."""

    assets: list[AssetModel] = field(default_factory=list)
    edges: list[EdgeModel] = field(default_factory=list)
    provenance: InventoryProvenance = field(default_factory=InventoryProvenance)
    replacements: dict[str, str] = field(default_factory=dict)

    def as_case(
        self,
        *,
        budget: float,
        entrypoints: Sequence[str] = (),
        targets: Sequence[str] = (),
    ) -> dict[str, object]:
        """Serialise to the case-file schema :mod:`qshield.experiments.benchmark` reads."""
        return {
            "_comment": (
                "Generated by `qshield ingest` from real artifacts. Fields marked "
                "ASSUMED in _provenance were NOT observed -- no certificate records "
                "sensitivity, exposure, data lifetime, business criticality, "
                "migration cost or rotation cadence. Review them, or run "
                "`qshield robustness` to check whether the recommendation depends "
                "on them."
            ),
            "budget": budget,
            "entrypoints": list(entrypoints) or _default_entrypoints(self),
            "targets": list(targets) or _default_targets(self),
            "assets": [_asset_to_dict(a) for a in self.assets],
            "edges": [
                {
                    "source": e.source,
                    "target": e.target,
                    "reliability": e.reliability,
                    "kind": e.kind.value,
                }
                for e in self.edges
            ],
            "replacements": dict(self.replacements),
            "_provenance": self.provenance.as_dict(),
        }


def load_certificates(paths: Iterable[str | Path]) -> list[tuple[x509.Certificate, str]]:
    """Read certificates from files or directories, tagged with their origin.

    A single file may hold a whole chain, which is how servers usually deploy
    them, so every PEM block in a file is read rather than only the first.
    """
    out: list[tuple[x509.Certificate, str]] = []
    for entry in paths:
        path = Path(entry)
        if path.is_dir():
            candidates = sorted(
                p
                for p in path.rglob("*")
                if p.is_file() and p.suffix.lower() in PEM_SUFFIXES | DER_SUFFIXES
            )
        else:
            candidates = [path]
        for candidate in candidates:
            raw = candidate.read_bytes()
            for cert in _parse_bundle(raw, str(candidate)):
                out.append((cert, str(candidate)))
    return out


def _parse_bundle(raw: bytes, origin: str) -> list[x509.Certificate]:
    """Every certificate in one file.

    Deployed bundles routinely concatenate a leaf with its whole chain, so
    reading only the first block would silently drop the issuers -- and the
    issuers are the assets that matter most here.
    """
    text = raw.lstrip()
    if text.startswith(b"-----BEGIN"):
        try:
            return list(x509.load_pem_x509_certificates(raw))
        except AttributeError:  # pragma: no cover - cryptography < 39
            return _split_pem(raw)
        except ValueError as exc:
            raise CertificateIngestError(f"{origin}: malformed PEM ({exc})") from exc
    try:
        return [x509.load_der_x509_certificate(raw)]
    except ValueError as exc:
        raise CertificateIngestError(
            f"{origin}: not a PEM or DER certificate ({exc})"
        ) from exc


def _split_pem(raw: bytes) -> list[x509.Certificate]:  # pragma: no cover
    marker = b"-----BEGIN CERTIFICATE-----"
    blocks = [marker + part for part in raw.split(marker)[1:]]
    return [x509.load_pem_x509_certificate(b) for b in blocks]


def fetch_tls_chain(host: str, port: int = 443, timeout: float = 10.0):
    """Retrieve the certificate chain a TLS endpoint presents.

    The chain is read *unverified*: the point is to inventory what is deployed,
    including expired or untrusted certificates, which are exactly the ones worth
    knowing about. Nothing is sent beyond a handshake and nothing is trusted.
    """
    context = ssl.create_default_context()
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    with (
        socket.create_connection((host, port), timeout=timeout) as raw,
        context.wrap_socket(raw, server_hostname=host) as tls,
    ):
        chain = getattr(tls._sslobj, "get_unverified_chain", None)
        if chain is None:  # pragma: no cover - no chain accessor on this build
            # Only the peer certificate is reachable; the issuers are lost, so
            # the trust hierarchy will be incomplete. Better than nothing, but
            # from_certificates will warn about the orphaned issuer.
            der = tls.getpeercert(binary_form=True)
            return [x509.load_der_x509_certificate(der)]
        return [
            x509.load_der_x509_certificate(c.public_bytes(_DER))
            for c in chain()
        ]


def from_certificates(
    certificates: Sequence[tuple[x509.Certificate, str]],
    *,
    now: datetime.datetime | None = None,
) -> Inventory:
    """Turn parsed certificates into assets and delegation edges."""
    now = now or datetime.datetime.now(datetime.timezone.utc)
    inventory = Inventory()

    # De-duplicate: the same CA appears in every chain that includes it.
    unique: dict[bytes, tuple[x509.Certificate, str]] = {}
    for cert, origin in certificates:
        unique.setdefault(cert.fingerprint(_sha256()), (cert, origin))

    entries = list(unique.values())
    names = _unique_names(entries)
    issued_counts = _issued_counts([c for c, _ in entries])

    for (cert, origin), name in zip(entries, names, strict=True):
        asset, record = _to_asset(cert, name, origin, issued_counts, now)
        inventory.assets.append(asset)
        inventory.provenance.add(record)
        if asset.algorithm not in inventory.replacements:
            replacement = _replacement_for(asset.algorithm)
            if replacement:
                inventory.replacements[asset.algorithm] = replacement

    inventory.edges.extend(_delegation_edges(entries, names))

    _add_warnings(inventory, entries, now)
    return inventory


def _to_asset(
    cert: x509.Certificate,
    name: str,
    origin: str,
    issued_counts: dict[bytes, int],
    now: datetime.datetime,
) -> tuple[AssetModel, AssetProvenance]:
    record = AssetProvenance(asset=name, origin=origin)

    algorithm = _algorithm_of(cert)
    record.observed("algorithm", f"subject public key info ({algorithm})")

    not_before, not_after = _validity(cert)
    validity_years = max(0.0, (not_after - not_before).days / DAYS_PER_YEAR)
    record.derived(
        "credential_validity_years",
        f"notAfter - notBefore = {not_before.date()} to {not_after.date()} "
        f"({validity_years:.2f} years)",
    )

    is_ca = _is_ca(cert)
    is_root = cert.subject == cert.issuer
    tier = "root" if (is_ca and is_root) else "intermediate" if is_ca else "leaf"
    record.derived("tier", f"basicConstraints CA={is_ca}, self-signed={is_root}")

    threat_class = ThreatClass.AUTHENTICATION
    verification_horizon = None
    if _has_eku(cert, ExtendedKeyUsageOID.CODE_SIGNING):
        # A codeSigning EKU is a statement that artifacts outlive the key.
        threat_class = ThreatClass.NON_REPUDIATION
        verification_horizon = ASSUMED_VERIFICATION_HORIZON_YEARS
        record.derived("threat_class", "extendedKeyUsage contains codeSigning")
        record.assumed(
            "verification_horizon_years",
            "how long signed artifacts must remain verifiable is not in the "
            "certificate; placeholder of "
            f"{ASSUMED_VERIFICATION_HORIZON_YEARS} years",
        )
    else:
        record.derived(
            "threat_class",
            "signature credential in live service (no codeSigning EKU)",
        )

    dependency_count = 1 + issued_counts.get(_ski_or_subject(cert), 0)
    record.derived(
        "dependency_count",
        f"1 + {dependency_count - 1} certificates issued by this subject in the inventory",
    )

    exposure = ASSUMED_EXPOSURE_CA if is_ca else ASSUMED_EXPOSURE_LEAF
    record.assumed(
        "exposure",
        f"not in X.509; {exposure} placeholder for a "
        f"{'certificate authority' if is_ca else 'end-entity certificate'}",
    )
    cost = (
        ASSUMED_COST_ROOT
        if tier == "root"
        else ASSUMED_COST_INTERMEDIATE
        if tier == "intermediate"
        else ASSUMED_COST_LEAF
    )
    record.assumed("migration_cost", f"not in X.509; {cost} placeholder for a {tier}")
    rotation = ASSUMED_ROTATION_HOURS_CA if is_ca else ASSUMED_ROTATION_HOURS_LEAF
    record.assumed("rotation_hours", f"not in X.509; {rotation} placeholder")
    record.assumed("sensitivity", f"not in X.509; {ASSUMED_SENSITIVITY} placeholder")
    record.assumed(
        "data_lifetime_years",
        f"not in X.509; {ASSUMED_DATA_LIFETIME_YEARS} placeholder. Unused for "
        "AUTHENTICATION assets, which read credential_validity_years instead.",
    )
    record.assumed(
        "business_criticality",
        f"not in X.509; {ASSUMED_BUSINESS_CRITICALITY} placeholder",
    )

    asset = AssetModel(
        name=name,
        algorithm=algorithm,
        sensitivity=ASSUMED_SENSITIVITY,
        exposure=exposure,
        data_lifetime_years=ASSUMED_DATA_LIFETIME_YEARS,
        dependency_count=dependency_count,
        rotation_hours=rotation,
        migration_cost=cost,
        business_criticality=ASSUMED_BUSINESS_CRITICALITY,
        controllable=True,
        threat_class=threat_class,
        credential_validity_years=validity_years,
        verification_horizon_years=verification_horizon,
    )
    return asset, record


def _delegation_edges(
    entries: Sequence[tuple[x509.Certificate, str]], names: Sequence[str]
) -> list[EdgeModel]:
    """One edge per issuer -> subject relation present in the inventory.

    Matching prefers the authority/subject key identifiers, because distinguished
    names are not unique in practice and cross-signed roots share them. It falls
    back to the DN when a certificate carries no identifiers.
    """
    by_ski: dict[bytes, str] = {}
    by_subject: dict[bytes, str] = {}
    for (cert, _), name in zip(entries, names, strict=True):
        ski = _extension_value(cert, x509.SubjectKeyIdentifier)
        if ski is not None:
            by_ski.setdefault(ski.digest, name)
        by_subject.setdefault(cert.subject.public_bytes(), name)

    edges: list[EdgeModel] = []
    seen: set[tuple[str, str]] = set()
    for (cert, _), name in zip(entries, names, strict=True):
        if cert.subject == cert.issuer:
            continue  # a self-signed root inherits from nobody
        issuer_name = None
        aki = _extension_value(cert, x509.AuthorityKeyIdentifier)
        if aki is not None and aki.key_identifier is not None:
            issuer_name = by_ski.get(aki.key_identifier)
        if issuer_name is None:
            issuer_name = by_subject.get(cert.issuer.public_bytes())
        if issuer_name is None or issuer_name == name:
            continue
        key = (issuer_name, name)
        if key in seen:
            continue
        seen.add(key)
        # A certificate authority's signature is the whole of the trust relation:
        # forging the issuer forges what it issued, completely.
        edges.append(EdgeModel(issuer_name, name, 1.0, EdgeKind.DELEGATION))
    return edges


def _add_warnings(
    inventory: Inventory,
    entries: Sequence[tuple[x509.Certificate, str]],
    now: datetime.datetime,
) -> None:
    provenance = inventory.provenance
    provenance.warn(
        "sensitivity, exposure, data_lifetime_years, business_criticality, "
        "migration_cost and rotation_hours are not recorded in X.509 and were "
        "filled with placeholders; run `qshield robustness` before acting on any "
        "number that depends on them"
    )

    expired = [
        name
        for (cert, _), name in zip(entries, _unique_names(entries), strict=True)
        if _validity(cert)[1] < now
    ]
    if expired:
        provenance.warn(
            f"{len(expired)} certificate(s) have already expired and are scored as "
            f"deployed anyway: {', '.join(sorted(expired)[:5])}"
            + ("..." if len(expired) > 5 else "")
        )

    orphans = _orphaned_issuers(entries)
    if orphans:
        provenance.warn(
            f"{len(orphans)} certificate(s) name an issuer that is not in the "
            "inventory, so their trust inheritance is missing and their risk is "
            "understated; add the issuing CA certificates to fix this"
        )

    if not any(e.kind is EdgeKind.DEPENDENCY for e in inventory.edges):
        provenance.warn(
            "no dependency edges: a certificate inventory records trust "
            "relations but not which service reaches which, so the attack-path "
            "term of the objective is inert and only node risk and trust "
            "inheritance are scored. Supply --entrypoints/--targets and "
            "dependency edges once the service topology is known"
        )

    if not inventory.replacements:
        provenance.warn(
            "no migratable algorithms found: every certificate is already "
            "post-quantum or uses a primitive with no defined replacement"
        )


def _orphaned_issuers(entries: Sequence[tuple[x509.Certificate, str]]) -> list[str]:
    subjects = {cert.subject.public_bytes() for cert, _ in entries}
    skis = {
        e.digest
        for cert, _ in entries
        if (e := _extension_value(cert, x509.SubjectKeyIdentifier)) is not None
    }
    out = []
    for (cert, _), name in zip(entries, _unique_names(entries), strict=True):
        if cert.subject == cert.issuer:
            continue
        aki = _extension_value(cert, x509.AuthorityKeyIdentifier)
        if aki is not None and aki.key_identifier is not None and aki.key_identifier in skis:
            continue
        if cert.issuer.public_bytes() in subjects:
            continue
        out.append(name)
    return out


def _algorithm_of(cert: x509.Certificate) -> str:
    """The subject's public key algorithm, in registry form.

    This is the key that would be migrated. The algorithm the certificate was
    *signed* with belongs to the issuer, and reaches this asset through the
    delegation edge instead.
    """
    key = cert.public_key()
    if isinstance(key, rsa.RSAPublicKey):
        size = key.key_size
        for candidate in (2048, 3072, 4096):
            if size <= candidate:
                return f"RSA-{candidate}"
        return "RSA-4096"
    if isinstance(key, ec.EllipticCurvePublicKey):
        return "ECDSA"
    if isinstance(key, ed25519.Ed25519PublicKey):
        return "ED25519"
    if isinstance(key, ed448.Ed448PublicKey):
        return "ED448"
    raise CertificateIngestError(
        f"unsupported public key type {type(key).__name__} in {cert.subject.rfc4514_string()!r}"
    )


def _replacement_for(algorithm: str) -> str | None:
    """Signature credentials migrate to a signature algorithm.

    ``qshield.algorithms.default_replacement`` maps RSA to ML-KEM, because key
    transport is the usual migration driver. Every asset built here is a signing
    credential, so that default is wrong and is overridden.
    """
    from ..algorithms import Family, family

    if family(algorithm) is not Family.SHOR_VULNERABLE:
        return None
    return "ML-DSA"


def _validity(cert: x509.Certificate) -> tuple[datetime.datetime, datetime.datetime]:
    # not_valid_before_utc/after_utc exist from cryptography 42; fall back for older.
    before = getattr(cert, "not_valid_before_utc", None)
    after = getattr(cert, "not_valid_after_utc", None)
    if before is None or after is None:  # pragma: no cover - older cryptography
        before = cert.not_valid_before.replace(tzinfo=datetime.timezone.utc)
        after = cert.not_valid_after.replace(tzinfo=datetime.timezone.utc)
    return before, after


def _is_ca(cert: x509.Certificate) -> bool:
    constraints = _extension_value(cert, x509.BasicConstraints)
    return bool(constraints and constraints.ca)


def _has_eku(cert: x509.Certificate, oid) -> bool:
    eku = _extension_value(cert, x509.ExtendedKeyUsage)
    return bool(eku and oid in eku)


def _extension_value(cert: x509.Certificate, extension_type):
    try:
        return cert.extensions.get_extension_for_class(extension_type).value
    except x509.ExtensionNotFound:
        return None


def _ski_or_subject(cert: x509.Certificate) -> bytes:
    ski = _extension_value(cert, x509.SubjectKeyIdentifier)
    return ski.digest if ski is not None else cert.subject.public_bytes()


def _issued_counts(certificates: Sequence[x509.Certificate]) -> dict[bytes, int]:
    """How many certificates in the inventory each subject issued."""
    by_ski: dict[bytes, bytes] = {}
    for cert in certificates:
        ski = _extension_value(cert, x509.SubjectKeyIdentifier)
        if ski is not None:
            by_ski[ski.digest] = ski.digest

    counts: dict[bytes, int] = {}
    for cert in certificates:
        if cert.subject == cert.issuer:
            continue
        aki = _extension_value(cert, x509.AuthorityKeyIdentifier)
        key = None
        if aki is not None and aki.key_identifier in by_ski:
            key = aki.key_identifier
        else:
            key = cert.issuer.public_bytes()
        counts[key] = counts.get(key, 0) + 1
    return counts


def _unique_names(entries: Sequence[tuple[x509.Certificate, str]]) -> list[str]:
    """Readable, stable, unique asset names.

    Common names collide constantly in real estates, so a colliding name is
    suffixed with a fingerprint prefix rather than silently merged -- two
    certificates with the same CN are two assets.
    """
    raw = [_display_name(cert) for cert, _ in entries]
    counts: dict[str, int] = {}
    for name in raw:
        counts[name] = counts.get(name, 0) + 1
    used: dict[str, int] = {}
    out: list[str] = []
    for (cert, _), name in zip(entries, raw, strict=True):
        if counts[name] == 1:
            out.append(name)
            continue
        used[name] = used.get(name, 0) + 1
        digest = cert.fingerprint(_sha256()).hex()[:8]
        out.append(f"{name}#{digest}")
    return out


def _display_name(cert: x509.Certificate) -> str:
    from cryptography.x509.oid import NameOID

    for oid in (NameOID.COMMON_NAME, NameOID.ORGANIZATION_NAME):
        values = cert.subject.get_attributes_for_oid(oid)
        if values:
            return str(values[0].value)
    return cert.subject.rfc4514_string()


def _sha256():
    from cryptography.hazmat.primitives import hashes

    return hashes.SHA256()


def _asset_to_dict(asset: AssetModel) -> dict[str, object]:
    out: dict[str, object] = {
        "name": asset.name,
        "algorithm": asset.algorithm,
        "sensitivity": round(asset.sensitivity, 6),
        "exposure": round(asset.exposure, 6),
        "data_lifetime_years": round(asset.data_lifetime_years, 6),
        "dependency_count": asset.dependency_count,
        "rotation_hours": round(asset.rotation_hours, 6),
        "migration_cost": round(asset.migration_cost, 6),
        "business_criticality": round(asset.business_criticality, 6),
        "controllable": asset.controllable,
        "threat_class": asset.effective_threat_class.value,
    }
    if asset.credential_validity_years is not None:
        out["credential_validity_years"] = round(asset.credential_validity_years, 6)
    if asset.verification_horizon_years is not None:
        out["verification_horizon_years"] = round(asset.verification_horizon_years, 6)
    return out


def _default_entrypoints(inventory: Inventory) -> list[str]:
    """Nothing, unless the inventory contains traversable dependencies.

    A certificate inventory on its own has no attack *paths*. Certificates relate
    to each other by delegation, which is dominance rather than traversal, and
    nothing in X.509 says which service depends on which. Inventing an entrypoint
    and a target here would manufacture a path term out of nothing; leaving them
    empty makes the path component correctly inert, and the report says so.

    Supply --entrypoints and --targets once you know how the services behind
    these certificates actually depend on each other.
    """
    return []


def _default_targets(inventory: Inventory) -> list[str]:
    return []
